[pytest]
# Configuración de pytest para pruebas
# Usar xdist para ejecutar pruebas en paralelo con 3 workers
addopts = -n 3 -q -s -vv --html=report.html --self-contained-html

testpaths = tests
python_files = test_*.py
python_functions = test_*