[pytest]
# -- CONFIGURACIÓN GENERAL DE PYTEST --
# -rfE (resumen de fallos y errores), --strict-markers para validar marcadores
# Opciones soportadas: --browser, --headed, --screenshot=only-on-failure|on|off,
# --video=retain-on-failure|on|off, --tracing=retain-on-failure|on|off
addopts = -s -rfE --strict-markers --browser chromium --headed --screenshot=only-on-failure --video=retain-on-failure --tracing=retain-on-failure

# Habilitar ejecución de pruebas asíncronas solo para tests marcados
asyncio_mode = auto

# Define el directorio raíz de las pruebas
testpaths = tests
# Patrón para identificar archivos de prueba
python_files = test_*.py
# Patrón para identificar funciones de prueba
python_functions = test_*
