[pytest]
# Configuración de pytest para pruebas asíncronas
# Removemos -n auto porque puede causar problemas con fixtures asíncronas
addopts = -s -vv --html=report.html --self-contained-html
asyncio_mode = auto

testpaths = tests
python_files = test_*.py
python_functions = test_*